version: "3"
services:
  web-application:
    image: repo.treescale.com/starinje/web-application:latest
    ports:
      - "5000:5000"
  data-service:
    image: "repo.treescale.com/starinje/data-service:latest"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  score-calculation-service:
    image: "repo.treescale.com/starinje/data-service:latest"
  mongo:
    image: "mongo"
